# This is the control file for Travis continuous integration system.
#
# It is used automatically for the repositories on Github if it's found in the
# root directory of the project.
language: cpp
sudo: required

matrix:
    include:
        - compiler: gcc
        - compiler: gcc
          env: wxCONFIGURE_FLAGS="--enable-utf8 --enable-utf8only --enable-monolithic"
        - dist: trusty
          compiler: gcc
          env: wxCONFIGURE_FLAGS="--enable-stl"
        - dist: trusty
          compiler: clang
          env: wxCONFIGURE_FLAGS="--disable-shared --disable-sys-libs"
        - os: osx
          osx_image: xcode6.4
          compiler: clang
          env:
             - wxMAKEFILE_FLAGS="CXXFLAGS=-std=c++11 CPPFLAGS=-stdlib=libc++ LDFLAGS=-stdlib=libc++"
             - wxCONFIGURE_FLAGS="--with-macosx-version-min=10.7 $wxMAKEFILE_FLAGS"

branches:
    only:
        - master
        - WX_3_0_BRANCH

notifications:
    email:
        recipients:
            - vadim@wxwidgets.org
        on_success: change
        on_failure: change

before_install:
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update                                 ; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y libcppunit-dev libgtk2.0-dev; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]  ; then brew update                                         ; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]  ; then brew install cppunit                                ; fi

script: bash build/tools/travis-ci.sh
